// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using BlockchainTx;
//
//    var blockchainTx = BlockchainTx.FromJson(jsonString);

namespace CryptoCityWallet.ExternalUtilities.Models
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class BlockchainTx
    {
        [JsonProperty("address")]
        public string Address { get; set; }

        [JsonProperty("total_received")]
        public long TotalReceived { get; set; }

        [JsonProperty("total_sent")]
        public long TotalSent { get; set; }

        [JsonProperty("balance")]
        public long Balance { get; set; }

        [JsonProperty("unconfirmed_balance")]
        public long UnconfirmedBalance { get; set; }

        [JsonProperty("final_balance")]
        public long FinalBalance { get; set; }

        [JsonProperty("n_tx")]
        public long NTx { get; set; }

        [JsonProperty("unconfirmed_n_tx")]
        public long UnconfirmedNTx { get; set; }

        [JsonProperty("final_n_tx")]
        public long FinalNTx { get; set; }

        [JsonProperty("txrefs")]
        public IEnumerable<Txref> Txrefs { get; set; }

        [JsonProperty("tx_url")]
        public Uri TxUrl { get; set; }
    }

    public partial class Txref : IEquatable<Txref>
    {
        [JsonProperty("tx_hash")]
        public string TxHash { get; set; }

        [JsonProperty("block_height")]
        public long BlockHeight { get; set; }

        [JsonProperty("tx_input_n")]
        public long TxInputN { get; set; }

        [JsonProperty("tx_output_n")]
        public long TxOutputN { get; set; }

        [JsonProperty("value")]
        private long _Value { get; set;}

        public long Value { get {
                if (TxOutputN < 0)
                {
                    this._Value = Math.Abs(this._Value) * -1;
                };
                return this._Value;
            }
            set { return; }
        }

        public long ValueFiat { get; set; }

        [JsonProperty("ref_balance")]
        public long RefBalance { get; set; }

        [JsonProperty("confirmations")]
        public long Confirmations { get; set; }

        [JsonProperty("confirmed")]
        public DateTimeOffset Confirmed { get; set; }

        [JsonProperty("double_spend")]
        public bool DoubleSpend { get; set; }

        [JsonProperty("spent", NullValueHandling = NullValueHandling.Ignore)]
        public bool? Spent { get; set; }

        [JsonProperty("spent_by", NullValueHandling = NullValueHandling.Ignore)]
        public string SpentBy { get; set; }

        public bool Equals(Txref other)
        {

            //Check whether the compared object is null. 
            if (Object.ReferenceEquals(other, null)) return false;

            //Check whether the compared object references the same data. 
            if (Object.ReferenceEquals(this, other)) return true;

            //Check whether the products' properties are equal. 
            return TxHash.Equals(other.TxHash);
        }

        // If Equals() returns true for a pair of objects  
        // then GetHashCode() must return the same value for these objects. 

        public override int GetHashCode()
        {
            
            //Get hash code for the Code field. 
            int hashProductCode = TxHash.GetHashCode();

            //Calculate the hash code for the product. 
            return hashProductCode;
        }
    }

    public partial class BlockchainTx
    {
        public static BlockchainTx FromJson(string json) => JsonConvert.DeserializeObject<BlockchainTx>(json, CryptoCityWallet.ExternalUtilities.Models.Converter.Settings);
    }

    public static class Serialize
    {
        public static string ToJson(this BlockchainTx self) => JsonConvert.SerializeObject(self, CryptoCityWallet.ExternalUtilities.Models.Converter.Settings);
    }

    internal static class Converter
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }
}
